# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Training Course on Next generation sequencing
tagline:             Training Course on Next generation sequencing
description:         NGS training
url:                 'https://bioinfo-dirty-jobs.github.io/NGSBASE/'
baseurl:             '/NGSBASE/'
twitter_username:
github_username:  bioinfo-dirty-jobs
pages_url: https://bioinfo-dirty-jobs.github.io/NGSBASE
github_url: https://bioinfo-dirty-jobs.github.io/NGSBASE

# Custom vars
version:             2.0

# Build settings
markdown: kramdown
